### ISSUE TITLE
Camera went black after a few seconds

### ISSUE THREAD

**Issue by porky11** [donkeyteethUX/kcam#1]
When starting the program, it seemed to work fine, then the camera went black.

I wouldn't exclude a technical problem on my side yet.

**Comment by donkeyteethUX** [comment]
My guess would be the call to `next_frame` failed (probably an error bubbled up from `v4l` for some reason). I added a bit of diagnostics. What output do you get from running the binary with `RUST_LOG=debug`?

**Comment by porky11** [comment]
I'm pretty sure it's because my camera had a loose contact. In most programs it wasn't a problem because it did automatically reconnect. Can't test it anymore, I have a new cam now.
