### ISSUE TITLE
"Failed to take photo: cannot find picture directory"

### ISSUE THREAD

**Issue by vi** [donkeyteethUX/kcam#11]
What is a picture directly? Current working directory is writable, what is the problem saving there?

At least error message should show the path to the directly that is not being found.

Obviously, the picture directly should be adjustable from CLI.

**Comment by donkeyteethUX** [comment]
Thanks for the report. That's an error from here: https://docs.rs/dirs/latest/dirs/fn.picture_dir.html which admittedly may not be super robust. Maybe `~/Pictures` was deleted.

Anyway, I'll fix it to save somewhere else if that happens. Adding a configurable save directory is a todo.

**Comment by vi** [comment]
> Maybe `~/Pictures` was deleted.

Or not created at all. I don't see it in `/etc/skel/` on Debian and don't remember `/sbin/adduser` creating it.

**Comment by donkeyteethUX** [comment]
Does it work now?

**Comment by donkeyteethUX** [comment]
> > Maybe `~/Pictures` was deleted.
> 
> Or not created at all. I don't see it in `/etc/skel/` on Debian and don't remember `/sbin/adduser` creating it.

Indeed it looks like[ Debian doesn't create these ](https://unix.stackexchange.com/questions/291634/why-are-folders-in-home-directory-documents-pictures-etc-created-only-after)default folders. Huh.

**Comment by vi** [comment]
It created the directory and saved a jpg into it. Picture size is not adjustable from within `kcam` (but I can switch it by issuing `ffmpeg -s ... -i /dev/video0` between kcam sessions).

Number of syscalls when saving a photo is linear depending on number of already saved photos:

```
[pid 32211] statx(12, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_BASIC_STATS|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0444, stx_size=4096, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=144, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_0.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=614400, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_1.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_2.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_3.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_4.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_5.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_6.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_7.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=2457600, ...}) = 0
[pid 32211] statx(AT_FDCWD, "/home/vi/Pictures/kcam/img_8.jpg", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffce93f9370) = -1 ENOENT (No such file or directory)
```

Would exponential growth, followed by binary search be more appropriate to find the name slot?
Or better naming files like `YYYYmmDD_HHMMSS.jpg`, with a tie-breaker only in case of multiple photos per second?

**Comment by vi** [comment]
```
$ rm -Rf ~/Pictures/
$ touch ~/Pictures
$ kcam
...
Failed to take photo: Not a directory (os error 20)
```

Still no mention of the path in error message. Is it the time for [`fs_err`](https://docs.rs/fs-err/latest/fs_err/)?

**Comment by vi** [comment]
```
kcam> Saved picture: /home/vi/Pictures/...

$ chmod 000 ~/Pictures

kcam> Saved picture: kcam/...

$ chmod 000 kcam

kcam> Failed to take photo: unable to write image. Caused by: Permission denied (os error 13)
```

Still no file path on error. It is not possible to make saving files "unbreakably robust", failure to save a file is always a possibility, so error message should be useful.

Also fallback to currently directory when home directory is not available may confuse users who expected to see incoming photos in `~/Pictures/kcam/`, but kcam suddenly starting saving them elsewhere (e.g. due to `/home` remounting readonly because of filesystem errors). `Saved picture: kcam/...` may be interpreted by end user as `Saved picture: ~/Pictures/kcam/...`, just with `~/Pictures` omitted - they both have `kcam` after all. One would see old photos saved by `kcam` and wonder why there is no new one even though `kcam` said it was saved successfully.

If you want to keep auto-fallback (iffy), `kcam` should at least show longer message when using it, e.g. `Failed to picture in ~/Pictures/...: permission denied. Saved picture: kcam/...`.

**Comment by donkeyteethUX** [comment]
I do appreciate the aggressive software testing, but that chmod example is pretty adversarial. I'm sure it's possible to break this simple software in many ways if you try. 

I'll add context to the error (and probably a CLI as you suggest) at some point. These are good suggestions (:

**Comment by vi** [comment]
> chmod example is pretty adversarial

Indeed, that example was specifically to get to the error message quickly and is not likely to be encountered outside of such synthetic testing scenarios.

But similar errors can happen naturally. For example:

* Filesystem being readonly (including auto-remount due to errors)
* Wrong `$HOME`.
* `~/Pictures` being a symlink to other location and that location being not mounted.
* `/home/` being on NFS and network error preventing reaching the NFS server.
* SELinux or similar security mechanism preventing access to `~/Pictures` even tough DAC should be allowing it.

To debug and resolve such errors a filesystem path where error has occurred is useful. Showing just "Permission denied" without the path is like showing "Cannot upload your picture: 401 Unauthorized" without mentioning the URL it was using to upload.

What's wrong with `fs_err` approach to just get the path appended to error message automatically?

**Comment by donkeyteethUX** [comment]
The project already uses anyhow, which displays full tracebacks via debug formatting. Adding `.with_context(|| format!("failed to save image to {:?}", path))` is all you need.
