### ISSUE TITLE
Do not assume /dev/video0

### ISSUE THREAD

**Issue by porky11** [donkeyteethUX/kcam#2]
I get a "No such file or directory" error when starting the app.

I already found out, where this comes from: My camera does not have /dev/video0, but only 1 and 2.

What I would do (in this order):

- [ ] iterate over all webcams and choose the first one, that's found
- [ ] generate a list of all found webcams and display them in UI (if possible using a meaningful name, if you can find one)
- [ ] recognize, when webcams are plugged in or out, automatically update the list, switch the currently selected camera if none is available

**Comment by donkeyteethUX** [comment]
Fair enough, thank you. Proper device discovery would be a nice improvement. Probably a new drop-down menu with available video devices.

I'd be happy to add this, unless you want to take a shot at it? I'm also willing to review/accept PRs!
