### ISSUE TITLE
osx support

### ISSUE THREAD

**Issue by dolpm** [donkeyteethUX/kcam#7]
Hey! I saw your project on r/rust! This sounded like something up my alley and I noticed it didn't support osx.

I created [this](https://github.com/DPM97/vod) which contains a subset of the functionality but has all of the boilerplate necessary to deal with all OSX if this was something you wanted to eventually add.

I'll also take a crack at it when I have the time.

**Comment by donkeyteethUX** [comment]
Cool! Definitely go for it if you want. I'm happy to review PRs, but I'm personally not a MacOS user so I can't help too much.

To do it properly, we'd want to abstract away the platform specific code from the gui code which would be a decent refactor.
